import { randomBytes } from "node:crypto";
import { Prisma, prismaClient } from "@jade/database";
import wireguardTools from "wireguard-tools.js";
import { hashSecret } from "./agentEnrollment";
import { enqueueAgentJob } from "./agentJobs";
import { dispatchQueuedJobsToOnlineAgent } from "../sockets/agents";

const VPN_TOKEN_PREFIX = "jade_vpn_hub_";
const TUNNEL_POOL_BASE = ipToNumber("100.64.0.0");
const TUNNEL_POOL_SIZE = 1 << 22;
const HUB_TUNNEL_IP = "100.64.0.0";
const DEFAULT_PERSISTENT_KEEPALIVE = 25;

type CreateVpnHubOptions = {
  name: string;
  endpointHost: string;
  endpointPort: number;
  publicKey: string;
  serviceToken?: string;
};

type VpnClientStatus =
  | "Pending"
  | "Ready"
  | "Delivered"
  | "Degraded"
  | "Disabled";

type CreateVpnClientOptions = {
  scopeId: string;
  scopeIds: string[];
  name: string;
  storePrivateKey?: boolean;
};

type VpnClientConfigResult = {
  privateKey: string;
  renderedConfig: string;
  configFileName: string;
};

type DeleteVpnClientOptions = {
  id: string;
  scopeIds: string[];
};

type ProvisionVpnPeerOptions = {
  serverId: string;
  scopeIds: string[];
  hubId?: string;
  wireguardPublicKey?: string;
};

type VpnPeerLookupOptions = {
  serverId: string;
  scopeIds: string[];
};

type VpnClientLookupOptions = {
  id: string;
  scopeIds: string[];
};

type ListVpnClientsOptions = {
  scopeIds: string[];
  includeInactive?: boolean;
};

type DeliverVpnConfigOptions = VpnPeerLookupOptions;

type HubAuth = {
  hubId: string;
  serviceToken: string;
  publicKey?: string;
};

type VisibleServerForVpn = Awaited<ReturnType<typeof findVisibleServerForVpn>>;
type VisiblePeerForVpn = VisibleServerForVpn["vpnPeers"][number];
type DeliveredVpnConfig = {
  serverId: string;
  configRevisionId: string;
  agentJobId: string;
};

function generateToken() {
  return `${VPN_TOKEN_PREFIX}${randomBytes(32).toString("base64url")}`;
}

function ipToNumber(ip: string) {
  return ip.split(".").reduce((value, octet) => {
    const parsed = Number(octet);
    if (!Number.isInteger(parsed) || parsed < 0 || parsed > 255) {
      throw new Error(`Invalid IPv4 address: ${ip}`);
    }
    return (value << 8) + parsed;
  }, 0) >>> 0;
}

function numberToIp(value: number) {
  return [
    (value >>> 24) & 255,
    (value >>> 16) & 255,
    (value >>> 8) & 255,
    value & 255,
  ].join(".");
}

function normalizePort(value: number) {
  if (!Number.isInteger(value) || value < 1 || value > 65535) {
    throw new VpnError("endpointPort must be between 1 and 65535", 400);
  }

  return value;
}

function normalizeRequiredString(value: string, field: string) {
  const trimmed = value.trim();
  if (!trimmed) {
    throw new VpnError(`${field} is required`, 400);
  }
  return trimmed;
}

function normalizeOptionalString(value: unknown) {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : null;
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "vpn-client";
}

function normalizeVpnClientStatus(
  value: unknown,
  fallback: VpnClientStatus = "Ready",
): VpnClientStatus {
  if (
    value === "Pending" ||
    value === "Ready" ||
    value === "Delivered" ||
    value === "Degraded" ||
    value === "Disabled"
  ) {
    return value;
  }

  return fallback;
}

async function getDefaultHub() {
  const hub = await prismaClient.vpnHub.findFirst({
    where: {
      deletedAt: null,
    },
    orderBy: {
      createdAt: "asc",
    },
  });

  if (!hub) {
    throw new VpnError("VPN hub has not been created", 409);
  }

  return hub;
}

async function resolveVpnHub(hubId?: string) {
  if (!hubId) {
    return await getDefaultHub();
  }

  const hub = await prismaClient.vpnHub.findFirst({
    where: {
      id: hubId,
      deletedAt: null,
    },
  });

  if (!hub) {
    throw new VpnError("VPN hub not found", 404);
  }

  return hub;
}

async function generateWireGuardKeyPair() {
  return await wireguardTools.key.genKey();
}

function renderVpnClientConfig({
  client,
  hub,
  privateKey,
  allowedIps,
}: {
  client: { name: string; tunnelIp: string };
  hub: { endpointHost: string; endpointPort: number; publicKey: string };
  privateKey: string;
  allowedIps: string[];
}): string {
  return [
    "# Generated by Jade VPN Client setup.",
    `# Client: ${client.name}`,
    "[Interface]",
    `PrivateKey = ${privateKey}`,
    `Address = ${client.tunnelIp}/32`,
    "",
    "[Peer]",
    `PublicKey = ${hub.publicKey}`,
    `Endpoint = ${hub.endpointHost}:${hub.endpointPort}`,
    `AllowedIPs = ${allowedIps.join(", ")}`,
    `PersistentKeepalive = ${DEFAULT_PERSISTENT_KEEPALIVE}`,
    "",
  ].join("\n");
}

function renderVpnClientConfigFromRecord({
  client,
  allowedIps,
  privateKey,
}: {
  client: {
    name: string;
    tunnelIp: string;
    hub: { endpointHost: string; endpointPort: number; publicKey: string };
  };
  allowedIps: string[];
  privateKey: string;
}) {
  return renderVpnClientConfig({
    client: {
      name: client.name,
      tunnelIp: client.tunnelIp,
    },
    hub: {
      endpointHost: client.hub.endpointHost,
      endpointPort: client.hub.endpointPort,
      publicKey: client.hub.publicKey,
    },
    privateKey,
    allowedIps,
  });
}

async function allocateTunnelIp(tx: Prisma.TransactionClient) {
  const [peers, clients] = await Promise.all([
    tx.vpnPeer.findMany({
      select: {
        tunnelIp: true,
      },
    }),
    tx.vpnClient.findMany({
      select: {
        tunnelIp: true,
      },
    }),
  ]);
  const allocated = new Set([
    ...peers.map((peer) => peer.tunnelIp),
    ...clients.map((client) => client.tunnelIp),
  ]);

  for (let offset = 1; offset < TUNNEL_POOL_SIZE - 1; offset += 1) {
    const tunnelIp = numberToIp(TUNNEL_POOL_BASE + offset);
    if (!allocated.has(tunnelIp)) {
      return tunnelIp;
    }
  }

  throw new VpnError("Jade VPN tunnel IP pool is exhausted", 507);
}

function getLatestAgentPublicKey(
  server: { agents: Array<{ wireguardPublicKey: string | null }> },
) {
  return server.agents.find((agent) => agent.wireguardPublicKey)?.wireguardPublicKey ?? null;
}

async function syncHubPublicKey({
  hub,
  publicKey,
}: {
  hub: Awaited<ReturnType<typeof authenticateHub>>;
  publicKey?: string;
}) {
  const normalizedPublicKey = normalizeOptionalString(publicKey);

  if (!normalizedPublicKey || normalizedPublicKey === hub.publicKey) {
    return hub;
  }

  return await prismaClient.vpnHub.update({
    where: {
      id: hub.id,
    },
    data: {
      publicKey: normalizedPublicKey,
      desiredStateVersion: {
        increment: 1,
      },
    },
  });
}

async function syncVisiblePeerPublicKey({
  server,
  peer,
}: {
  server: VisibleServerForVpn;
  peer: VisiblePeerForVpn;
}): Promise<VisiblePeerForVpn> {
  const publicKey = getLatestAgentPublicKey(server);

  if (!publicKey || publicKey === peer.publicKey) {
    return peer;
  }

  return await prismaClient.$transaction(async (tx) => {
    await tx.vpnHub.update({
      where: {
        id: peer.hubId,
      },
      data: {
        desiredStateVersion: {
          increment: 1,
        },
      },
    });

    return await tx.vpnPeer.update({
      where: {
        id: peer.id,
      },
      data: {
        publicKey,
      },
      include: {
        hub: true,
        configRevisions: {
          orderBy: {
            revision: "desc",
          },
          take: 1,
        },
      },
    });
  });
}

async function findVisibleServerForVpn({
  serverId,
  scopeIds,
}: VpnPeerLookupOptions) {
  if (scopeIds.length === 0) {
    throw new VpnError("Server not found", 404);
  }

  const server = await prismaClient.server.findFirst({
    where: {
      id: serverId,
      scopeId: {
        in: scopeIds,
      },
      deletedAt: null,
    },
    include: {
      agents: {
        where: {
          deletedAt: null,
        },
        orderBy: [
          {
            lastSeenAt: "desc",
          },
          {
            createdAt: "desc",
          },
        ],
      },
      vpnPeers: {
        where: {
          deletedAt: null,
        },
        include: {
          hub: true,
          configRevisions: {
            orderBy: {
              revision: "desc",
            },
            take: 1,
          },
        },
      },
    },
  });

  if (!server) {
    throw new VpnError("Server not found", 404);
  }

  return server;
}

async function findVisibleVpnClient({
  id,
  scopeIds,
  includeInactive = false,
}: VpnClientLookupOptions & { includeInactive?: boolean }) {
  if (scopeIds.length === 0) {
    return null;
  }

  return await prismaClient.vpnClient.findFirst({
    where: {
      id,
      scopeId: {
        in: scopeIds,
      },
      ...(includeInactive ? {} : { deletedAt: null }),
    },
    include: {
      hub: {
        select: {
          id: true,
          name: true,
          endpointHost: true,
          endpointPort: true,
          publicKey: true,
          status: true,
        },
      },
      scope: {
        select: {
          id: true,
          name: true,
          type: true,
        },
      },
    },
  });
}

function toPublicVpnClient<T extends { privateKey: string | null }>(client: T) {
  const { privateKey, ...rest } = client;

  return {
    ...rest,
    privateKeyStored: privateKey !== null,
  };
}

async function getPeerForVisibleServer(
  options: VpnPeerLookupOptions,
): Promise<{ server: VisibleServerForVpn; peer: VisiblePeerForVpn }> {
  const server = await findVisibleServerForVpn(options);
  const visiblePeer = server.vpnPeers[0];

  if (!visiblePeer) {
    throw new VpnError("VPN peer has not been provisioned for this server", 404);
  }

  const peer = await syncVisiblePeerPublicKey({ server, peer: visiblePeer });

  return { server, peer };
}

async function getSameScopePeers({
  peerId,
  hubId,
  scopeId,
}: {
  peerId: string;
  hubId: string;
  scopeId: string | null;
}) {
  if (!scopeId) {
    return [];
  }

  return await prismaClient.vpnPeer.findMany({
    where: {
      id: {
        not: peerId,
      },
      hubId,
      enabled: true,
      deletedAt: null,
      server: {
        scopeId,
        deletedAt: null,
      },
    },
    orderBy: {
      tunnelIp: "asc",
    },
  });
}

async function getClientAllowedIps({
  tx,
  hubId,
}: {
  tx: Prisma.TransactionClient;
  hubId: string;
}) {
  const peers = await tx.vpnPeer.findMany({
    where: {
      hubId,
      enabled: true,
      deletedAt: null,
    },
    orderBy: {
      tunnelIp: "asc",
    },
    select: {
      tunnelIp: true,
    },
  });
  const clients = await tx.vpnClient.findMany({
    where: {
      hubId,
      enabled: true,
      deletedAt: null,
    },
    select: {
      tunnelIp: true,
    },
  });
  const allowedIps = new Set<string>([
    `${HUB_TUNNEL_IP}/32`,
    ...peers.map((peer) => `${peer.tunnelIp}/32`),
    ...clients.map((client) => `${client.tunnelIp}/32`),
  ]);

  return [...allowedIps];
}

async function getHubAllowedClientIps({
  hubId,
  excludeTunnelIp,
}: {
  hubId: string;
  excludeTunnelIp?: string;
}) {
  const [peers, clients] = await Promise.all([
    prismaClient.vpnPeer.findMany({
      where: {
        hubId,
        enabled: true,
        deletedAt: null,
      },
      select: {
        tunnelIp: true,
      },
    }),
    prismaClient.vpnClient.findMany({
      where: {
        hubId,
        enabled: true,
        deletedAt: null,
      },
      select: {
        tunnelIp: true,
      },
    }),
  ]);

  return [
    ...new Set([
      `${HUB_TUNNEL_IP}/32`,
      ...peers.map((peer) => `${peer.tunnelIp}/32`),
      ...clients
        .filter((client) => client.tunnelIp !== excludeTunnelIp)
        .map((client) => `${client.tunnelIp}/32`),
    ]),
  ];
}

async function getHubClientTunnelIps({
  hubId,
}: {
  hubId: string;
}) {
  const clients = await prismaClient.vpnClient.findMany({
    where: {
      hubId,
      enabled: true,
      deletedAt: null,
    },
    select: {
      tunnelIp: true,
    },
    orderBy: {
      tunnelIp: "asc",
    },
  });

  return clients.map((client) => `${client.tunnelIp}/32`);
}

async function refreshClientScopePeerConfigs({
  hubId,
  scopeIds,
}: {
  hubId: string;
  scopeIds: string[];
}) {
  const visibleServerIds = await getHubPeerServerIdsForDelivery({
    hubId,
    scopeIds,
  });

  if (visibleServerIds.length === 0) {
    return;
  }

  await Promise.all(
    visibleServerIds.map((serverId) =>
      deliverVpnConfig({
        serverId,
        scopeIds,
      }),
    ),
  );
}

async function bumpHubDesiredState(
  tx: Prisma.TransactionClient,
  hubId: string,
) {
  await tx.vpnHub.update({
    where: {
      id: hubId,
    },
    data: {
      desiredStateVersion: {
        increment: 1,
      },
    },
  });
}

export async function getVpnHubs() {
  return await prismaClient.vpnHub.findMany({
    where: {
      deletedAt: null,
    },
    orderBy: {
      createdAt: "asc",
    },
    select: {
      id: true,
      name: true,
      endpointHost: true,
      endpointPort: true,
      publicKey: true,
      status: true,
      lastSeenAt: true,
      desiredStateVersion: true,
      createdAt: true,
      updatedAt: true,
    },
  });
}

export async function createVpnHub({
  name,
  endpointHost,
  endpointPort,
  publicKey,
  serviceToken,
}: CreateVpnHubOptions) {
  const token = serviceToken?.trim() || generateToken();
  const hub = await prismaClient.vpnHub.create({
    data: {
      name: normalizeRequiredString(name, "name"),
      endpointHost: normalizeRequiredString(endpointHost, "endpointHost"),
      endpointPort: normalizePort(endpointPort),
      publicKey: normalizeRequiredString(publicKey, "publicKey"),
      serviceTokenHash: hashSecret(token),
    },
  });

  return {
    id: hub.id,
    name: hub.name,
    endpointHost: hub.endpointHost,
    endpointPort: hub.endpointPort,
    publicKey: hub.publicKey,
    status: hub.status,
    lastSeenAt: hub.lastSeenAt,
    desiredStateVersion: hub.desiredStateVersion,
    createdAt: hub.createdAt,
    updatedAt: hub.updatedAt,
    serviceToken: token,
  };
}

export async function getVpnPeers({ scopeIds }: { scopeIds: string[] }) {
  if (scopeIds.length === 0) {
    return [];
  }

  return await prismaClient.vpnPeer.findMany({
    where: {
      deletedAt: null,
      server: {
        scopeId: {
          in: scopeIds,
        },
        deletedAt: null,
      },
    },
    include: {
      hub: {
        select: {
          id: true,
          name: true,
          endpointHost: true,
          endpointPort: true,
          publicKey: true,
          status: true,
          desiredStateVersion: true,
        },
      },
      server: {
        select: {
          id: true,
          name: true,
          scopeId: true,
        },
      },
      configRevisions: {
        orderBy: {
          revision: "desc",
        },
        take: 1,
      },
    },
    orderBy: {
      createdAt: "desc",
    },
  });
}

export async function getVpnClients({
  scopeIds,
  includeInactive = false,
}: ListVpnClientsOptions) {
  if (scopeIds.length === 0) {
    return [];
  }

  const clients = await prismaClient.vpnClient.findMany({
    where: {
      scopeId: {
        in: scopeIds,
      },
      ...(includeInactive ? {} : { deletedAt: null }),
    },
    include: {
      hub: {
        select: {
          id: true,
          name: true,
          endpointHost: true,
          endpointPort: true,
          status: true,
        },
      },
      scope: {
        select: {
          id: true,
          name: true,
          type: true,
        },
      },
    },
    orderBy: {
      createdAt: "desc",
    },
  });

  return clients.map((client) => toPublicVpnClient(client));
}

export async function getVpnClientById({
  id,
  scopeIds,
}: VpnClientLookupOptions) {
  const client = await findVisibleVpnClient({
    id,
    scopeIds,
  });

  if (!client) {
    throw new VpnError("VPN client not found", 404);
  }

  return toPublicVpnClient(client);
}

export async function getVpnClientConfig({
  id,
  scopeIds,
}: VpnClientLookupOptions) {
  const client = await findVisibleVpnClient({
    id,
    scopeIds,
  });

  if (!client) {
    throw new VpnError("VPN client not found", 404);
  }

  if (!client.privateKey) {
    throw new VpnError(
      "VPN client config is only available for regular mode clients",
      409,
    );
  }

  const allowedIps = await getHubAllowedClientIps({
    hubId: client.hubId,
    excludeTunnelIp: client.tunnelIp,
  });

  return {
    configFileName: `${slugify(client.name)}.conf`,
    renderedConfig: renderVpnClientConfigFromRecord({
      client,
      allowedIps,
      privateKey: client.privateKey,
    }),
  };
}

export async function createVpnClient({
  scopeId,
  scopeIds,
  name,
  storePrivateKey = false,
}: CreateVpnClientOptions) {
  const hub = await getDefaultHub();

  const createdClient = await prismaClient.$transaction(async (tx) => {
    const tunnelIp = await allocateTunnelIp(tx);
    const keyPair = await generateWireGuardKeyPair();
    const normalizedName = normalizeRequiredString(name, "name");
    const normalizedScopeId = normalizeRequiredString(scopeId, "scopeId");
    const allowedIps = await getClientAllowedIps({
      tx,
      hubId: hub.id,
    });
    const renderedConfig = renderVpnClientConfig({
      client: {
        name: normalizedName,
        tunnelIp,
      },
      hub,
      privateKey: keyPair.privateKey,
      allowedIps,
    });

    const client = await tx.vpnClient.create({
      data: {
        scopeId: normalizedScopeId,
        hubId: hub.id,
        name: normalizedName,
        tunnelIp,
        publicKey: keyPair.publicKey,
        privateKey: storePrivateKey ? keyPair.privateKey : null,
      },
      include: {
        hub: {
          select: {
            id: true,
            name: true,
            endpointHost: true,
            endpointPort: true,
            status: true,
          },
        },
        scope: {
          select: {
            id: true,
            name: true,
            type: true,
          },
        },
      },
    });

    await bumpHubDesiredState(tx, hub.id);

    const publicClient = toPublicVpnClient(client);

    return {
      ...publicClient,
      configFileName: `${slugify(client.name)}.conf`,
      renderedConfig,
      privateKey: keyPair.privateKey,
    } satisfies VpnClientConfigResult & typeof publicClient;
  });

  await refreshClientScopePeerConfigs({
    hubId: createdClient.hubId,
    scopeIds,
  });

  return createdClient;
}

type UpdateVpnClientOptions = {
  id: string;
  scopeIds: string[];
  name?: string;
  publicKey?: string;
  hubId?: string;
  status?: VpnClientStatus;
  enabled?: boolean;
};

export async function updateVpnClient({
  id,
  scopeIds,
  name,
  publicKey,
  hubId,
  status,
  enabled,
}: UpdateVpnClientOptions) {
  const client = await getVpnClientById({
    id,
    scopeIds,
  });
  const hub = hubId ? await resolveVpnHub(hubId) : client.hub;

  const updatedClient = await prismaClient.$transaction(async (tx) => {
    const updatedClient = await tx.vpnClient.update({
      where: {
        id: client.id,
      },
      data: {
        ...(name === undefined
          ? {}
          : { name: normalizeRequiredString(name, "name") }),
        ...(publicKey === undefined
          ? {}
          : { publicKey: normalizeRequiredString(publicKey, "publicKey") }),
        ...(hubId === undefined ? {} : { hubId: hub.id }),
        ...(status === undefined
          ? {}
          : { status: normalizeVpnClientStatus(status, client.status) }),
        ...(enabled === undefined ? {} : { enabled }),
      },
      include: {
        hub: {
          select: {
            id: true,
            name: true,
            endpointHost: true,
            endpointPort: true,
            status: true,
          },
        },
        scope: {
          select: {
            id: true,
            name: true,
            type: true,
          },
        },
      },
    });

    if (updatedClient.hubId !== client.hubId) {
      await Promise.all([
        bumpHubDesiredState(tx, client.hubId),
        bumpHubDesiredState(tx, updatedClient.hubId),
      ]);
    } else if (
      name !== undefined ||
      publicKey !== undefined ||
      hubId !== undefined ||
      status !== undefined ||
      enabled !== undefined
    ) {
      await bumpHubDesiredState(tx, updatedClient.hubId);
    }

    return updatedClient;
  });

  if (updatedClient.hubId !== client.hubId) {
    await Promise.all([
      refreshClientScopePeerConfigs({
        hubId: client.hubId,
        scopeIds,
      }),
      refreshClientScopePeerConfigs({
        hubId: updatedClient.hubId,
        scopeIds,
      }),
    ]);
  } else {
    await refreshClientScopePeerConfigs({
      hubId: updatedClient.hubId,
      scopeIds,
    });
  }

  return toPublicVpnClient(updatedClient);
}

export async function deleteVpnClient({
  id,
  scopeIds,
}: DeleteVpnClientOptions) {
  const client = await getVpnClientById({
    id,
    scopeIds,
  });

  const deletedClient = await prismaClient.$transaction(async (tx) => {
    const deletedClient = await tx.vpnClient.update({
      where: {
        id: client.id,
      },
      data: {
        enabled: false,
        status: "Disabled",
        deletedAt: new Date(),
      },
      include: {
        hub: {
          select: {
            id: true,
            name: true,
            endpointHost: true,
            endpointPort: true,
            status: true,
          },
        },
        scope: {
          select: {
            id: true,
            name: true,
            type: true,
          },
        },
      },
    });

    await bumpHubDesiredState(tx, deletedClient.hubId);

    return deletedClient;
  });

  await refreshClientScopePeerConfigs({
    hubId: client.hubId,
    scopeIds,
  });

  return toPublicVpnClient(deletedClient);
}

export async function provisionVpnPeer({
  serverId,
  scopeIds,
  hubId,
  wireguardPublicKey,
}: ProvisionVpnPeerOptions) {
  const server = await findVisibleServerForVpn({ serverId, scopeIds });
  const hub = hubId
    ? await prismaClient.vpnHub.findFirst({
        where: {
          id: hubId,
          deletedAt: null,
        },
      })
    : await getDefaultHub();

  if (!hub) {
    throw new VpnError("VPN hub not found", 404);
  }

  const publicKey = wireguardPublicKey?.trim() || getLatestAgentPublicKey(server);

  if (!publicKey) {
    throw new VpnError("Server agent has not reported a WireGuard public key", 409);
  }

  return await prismaClient.$transaction(async (tx) => {
    const existingPeer = await tx.vpnPeer.findUnique({
      where: {
        serverId_hubId: {
          serverId: server.id,
          hubId: hub.id,
        },
      },
    });
    const tunnelIp = existingPeer?.tunnelIp ?? (await allocateTunnelIp(tx));
    const peer = existingPeer
      ? await tx.vpnPeer.update({
          where: {
            id: existingPeer.id,
          },
          data: {
            publicKey,
            enabled: true,
            status: "Ready",
            deletedAt: null,
          },
        })
      : await tx.vpnPeer.create({
          data: {
            serverId: server.id,
            hubId: hub.id,
            tunnelIp,
            publicKey,
            status: "Ready",
          },
        });

    await tx.vpnRoute.upsert({
      where: {
        peerId_cidr: {
          peerId: peer.id,
          cidr: `${peer.tunnelIp}/32`,
        },
      },
      create: {
        peerId: peer.id,
        cidr: `${peer.tunnelIp}/32`,
      },
      update: {
        enabled: true,
      },
    });

    await tx.vpnHub.update({
      where: {
        id: hub.id,
      },
      data: {
        desiredStateVersion: {
          increment: 1,
        },
      },
    });

    return peer;
  });
}

export async function renderSpokeConfig(options: VpnPeerLookupOptions) {
  const { server, peer } = await getPeerForVisibleServer(options);
  const sameScopePeers = await getSameScopePeers({
    peerId: peer.id,
    hubId: peer.hubId,
    scopeId: server.scopeId,
  });
  const hubClientIps = await getHubClientTunnelIps({
    hubId: peer.hubId,
  });
  const allowedIps = [
    `${HUB_TUNNEL_IP}/32`,
    ...sameScopePeers.map((sameScopePeer) => `${sameScopePeer.tunnelIp}/32`),
    ...hubClientIps,
  ];
  const endpoint = `${peer.hub.endpointHost}:${peer.hub.endpointPort}`;
  const renderedConfig = [
    "[Interface]",
    `Address = ${peer.tunnelIp}/32`,
    "PrivateKey = <agent-local-wireguard-private-key>",
    "",
    "[Peer]",
    `PublicKey = ${peer.hub.publicKey}`,
    `Endpoint = ${endpoint}`,
    ...(allowedIps.length > 0 ? [`AllowedIPs = ${allowedIps.join(", ")}`] : []),
    `PersistentKeepalive = ${DEFAULT_PERSISTENT_KEEPALIVE}`,
    "",
  ].join("\n");

  return {
    peer,
    serverId: server.id,
    hub: peer.hub,
    tunnelIp: peer.tunnelIp,
    endpoint,
    allowedIps,
    renderedConfig,
  };
}

export async function createVpnConfigRevision(options: VpnPeerLookupOptions) {
  const spokeConfig = await renderSpokeConfig(options);
  const latest = await prismaClient.vpnConfigRevision.findFirst({
    where: {
      peerId: spokeConfig.peer.id,
    },
    orderBy: {
      revision: "desc",
    },
    select: {
      revision: true,
    },
  });
  const revision = (latest?.revision ?? 0) + 1;
  const payload = {
    mode: "dry-run",
    configRevisionId: null,
    serverId: spokeConfig.serverId,
    peerId: spokeConfig.peer.id,
    hubId: spokeConfig.hub.id,
    tunnelIp: spokeConfig.tunnelIp,
    hubEndpoint: spokeConfig.endpoint,
    allowedIps: spokeConfig.allowedIps,
    renderedConfig: spokeConfig.renderedConfig,
  };

  const configRevision = await prismaClient.vpnConfigRevision.create({
    data: {
      peerId: spokeConfig.peer.id,
      hubId: spokeConfig.hub.id,
      revision,
      desiredStateVersion: spokeConfig.hub.desiredStateVersion,
      renderedConfig: spokeConfig.renderedConfig,
      payload: payload as Prisma.InputJsonValue,
    },
  });

  const finalPayload = {
    ...payload,
    configRevisionId: configRevision.id,
  };

  await prismaClient.vpnConfigRevision.update({
    where: {
      id: configRevision.id,
    },
    data: {
      payload: finalPayload as Prisma.InputJsonValue,
    },
  });
  await prismaClient.vpnPeer.update({
    where: {
      id: spokeConfig.peer.id,
    },
    data: {
      lastConfigRevisionId: configRevision.id,
    },
  });

  return {
    ...configRevision,
    payload: finalPayload,
  };
}

async function deliverVpnConfigToServer(options: DeliverVpnConfigOptions): Promise<DeliveredVpnConfig> {
  const { server, peer } = await getPeerForVisibleServer(options);
  const agent = server.agents[0];

  if (!agent) {
    throw new VpnError("Server has no enrolled agent", 409);
  }

  const configRevision = await createVpnConfigRevision(options);
  const job = await enqueueAgentJob({
    agentId: agent.id,
    type: "ConfigureVpn",
    payload: configRevision.payload as Prisma.InputJsonValue,
  });

  await prismaClient.$transaction([
    prismaClient.vpnConfigRevision.update({
      where: {
        id: configRevision.id,
      },
      data: {
        agentJobId: job.id,
        deliveryStatus: "Delivered",
      },
    }),
    prismaClient.vpnPeer.update({
      where: {
        id: peer.id,
      },
      data: {
        status: "Delivered",
      },
    }),
  ]);

  await dispatchQueuedJobsToOnlineAgent(agent.id);

  return {
    serverId: server.id,
    configRevisionId: configRevision.id,
    agentJobId: job.id,
  };
}

async function getScopePeerServerIdsForDelivery({
  hubId,
  scopeId,
  scopeIds,
}: {
  hubId: string;
  scopeId: string | null;
  scopeIds: string[];
}) {
  if (!scopeId || scopeIds.length === 0) {
    return [];
  }

  if (!scopeIds.includes(scopeId)) {
    return [];
  }

  const peers = await prismaClient.vpnPeer.findMany({
    where: {
      hubId,
      enabled: true,
      deletedAt: null,
      server: {
        scopeId,
        deletedAt: null,
      },
    },
    select: {
      serverId: true,
      server: {
        select: {
          agents: {
            where: {
              deletedAt: null,
            },
            orderBy: [
              {
                lastSeenAt: "desc",
              },
              {
                createdAt: "desc",
              },
            ],
            select: {
              id: true,
            },
            take: 1,
          },
        },
      },
    },
    orderBy: {
      createdAt: "asc",
    },
  });

  return peers
    .filter((peer) => peer.server.agents.length > 0)
    .map((peer) => peer.serverId);
}

async function getHubPeerServerIdsForDelivery({
  hubId,
  scopeIds,
}: {
  hubId: string;
  scopeIds: string[];
}) {
  if (scopeIds.length === 0) {
    return [];
  }

  const peers = await prismaClient.vpnPeer.findMany({
    where: {
      hubId,
      enabled: true,
      deletedAt: null,
      server: {
        scopeId: {
          in: scopeIds,
        },
        deletedAt: null,
      },
    },
    select: {
      serverId: true,
      server: {
        select: {
          agents: {
            where: {
              deletedAt: null,
            },
            orderBy: [
              {
                lastSeenAt: "desc",
              },
              {
                createdAt: "desc",
              },
            ],
            select: {
              id: true,
            },
            take: 1,
          },
        },
      },
    },
    orderBy: {
      createdAt: "asc",
    },
  });

  return peers
    .filter((peer) => peer.server.agents.length > 0)
    .map((peer) => peer.serverId);
}

export async function deliverVpnConfig(options: DeliverVpnConfigOptions) {
  const primary = await deliverVpnConfigToServer(options);
  const { server, peer } = await getPeerForVisibleServer(options);
  const siblingServerIds = await getScopePeerServerIdsForDelivery({
    hubId: peer.hubId,
    scopeId: server.scopeId,
    scopeIds: options.scopeIds,
  });

  const refreshedPeers = (
    await Promise.all(
      siblingServerIds
        .filter((serverId) => serverId !== server.id)
        .map(async (serverId) => {
          try {
            return await deliverVpnConfigToServer({
              serverId,
              scopeIds: options.scopeIds,
            });
          } catch (error) {
            if (
              error instanceof VpnError &&
              (error.statusCode === 404 || error.statusCode === 409)
            ) {
              return null;
            }

            throw error;
          }
        }),
    )
  ).filter(Boolean);

  return {
    configRevisionId: primary.configRevisionId,
    agentJobId: primary.agentJobId,
    refreshedPeerCount: refreshedPeers.length + 1,
  };
}

export async function getHubDesiredState({ hubId, serviceToken, publicKey }: HubAuth) {
  const authenticatedHub = await authenticateHub({ hubId, serviceToken });
  const hub = await syncHubPublicKey({
    hub: authenticatedHub,
    publicKey,
  });
  const peers = await prismaClient.vpnPeer.findMany({
    where: {
      hubId: hub.id,
      enabled: true,
      deletedAt: null,
      server: {
        deletedAt: null,
      },
    },
    include: {
      server: {
        select: {
          id: true,
          scopeId: true,
          agents: {
            where: {
              deletedAt: null,
            },
            orderBy: [
              {
                lastSeenAt: "desc",
              },
              {
                createdAt: "desc",
              },
            ],
            select: {
              wireguardPublicKey: true,
            },
          },
        },
      },
      routes: {
        where: {
          enabled: true,
        },
        orderBy: {
          cidr: "asc",
        },
      },
    },
    orderBy: {
      tunnelIp: "asc",
    },
  });
  const clients = await prismaClient.vpnClient.findMany({
    where: {
      hubId: hub.id,
      enabled: true,
      deletedAt: null,
      scope: {
        deletedAt: null,
      },
    },
    include: {
      scope: {
        select: {
          id: true,
        },
      },
    },
    orderBy: {
      tunnelIp: "asc",
    },
  });
  const peerStates = peers.map((peer) => ({
    peer,
    publicKey: getLatestAgentPublicKey(peer.server) ?? peer.publicKey,
  }));
  const clientStates = clients.map((client) => ({
    client,
    publicKey: client.publicKey,
  }));
  const stalePeers = peerStates.filter(({ peer, publicKey }) => publicKey !== peer.publicKey);
  const staleClients = clientStates.filter(({ client, publicKey }) => publicKey !== client.publicKey);
  const syncedHub =
    stalePeers.length > 0 || staleClients.length > 0
      ? await prismaClient.$transaction(async (tx) => {
          await Promise.all(
            stalePeers.map(({ peer, publicKey }) =>
              tx.vpnPeer.update({
                where: {
                  id: peer.id,
                },
                data: {
                  publicKey,
                },
              }),
            ),
          );
          await Promise.all(
            staleClients.map(({ client, publicKey }) =>
              tx.vpnClient.update({
                where: {
                  id: client.id,
                },
                data: {
                  publicKey,
                },
              }),
            ),
          );

          return await tx.vpnHub.update({
            where: {
              id: hub.id,
            },
            data: {
              desiredStateVersion: {
                increment: 1,
              },
            },
          });
        })
      : hub;

  return {
    hub: {
      id: syncedHub.id,
      name: syncedHub.name,
      endpointHost: syncedHub.endpointHost,
      endpointPort: syncedHub.endpointPort,
      publicKey: syncedHub.publicKey,
      desiredStateVersion: syncedHub.desiredStateVersion,
    },
    peers: peerStates.map(({ peer, publicKey }) => ({
      id: peer.id,
      serverId: peer.serverId,
      scopeId: peer.server.scopeId,
      tunnelIp: `${peer.tunnelIp}/32`,
      publicKey,
      allowedIps: [`${peer.tunnelIp}/32`],
      routes: peer.routes.map((route) => route.cidr),
    })).concat(
      clients.map((client) => ({
        id: client.id,
        serverId: client.id,
        scopeId: client.scopeId,
        tunnelIp: `${client.tunnelIp}/32`,
        publicKey: client.publicKey,
        allowedIps: [`${client.tunnelIp}/32`],
        routes: [`${client.tunnelIp}/32`],
      })),
    ),
  };
}

export async function recordHubStatus({
  hubId,
  serviceToken,
  status,
  publicKey,
}: HubAuth & { status: unknown }) {
  const authenticatedHub = await authenticateHub({ hubId, serviceToken });
  const hub = await syncHubPublicKey({
    hub: authenticatedHub,
    publicKey,
  });
  const normalizedStatus =
    status === "Online" || status === "Offline" || status === "Degraded"
      ? status
      : "Unknown";

  return await prismaClient.vpnHub.update({
    where: {
      id: hub.id,
    },
    data: {
      status: normalizedStatus,
      lastSeenAt: new Date(),
    },
    select: {
      id: true,
      status: true,
      lastSeenAt: true,
    },
  });
}

async function authenticateHub({ hubId, serviceToken }: HubAuth) {
  const hub = await prismaClient.vpnHub.findFirst({
    where: {
      id: hubId,
      serviceTokenHash: hashSecret(serviceToken),
      deletedAt: null,
    },
  });

  if (!hub) {
    throw new VpnError("Invalid VPN hub credentials", 401);
  }

  return hub;
}

export async function searchVpnResources({
  query,
  scopeIds,
}: {
  query: string;
  scopeIds: string[];
}): Promise<Array<{
  type: "vpn_client" | "vpn_peer" | "server" | "scope" | "resource";
  id: string;
  name: string;
  scopeId: string | null;
  hubId: string | null;
  status?: string;
}>> {
  if (scopeIds.length === 0 || !query.trim()) {
    return [];
  }

  const [clients, peers, servers, scopes] = await Promise.all([
    prismaClient.vpnClient.findMany({
      where: {
        scopeId: { in: scopeIds },
        deletedAt: null,
        name: { contains: query.trim(), mode: "insensitive" },
      },
      select: {
        id: true,
        name: true,
        scopeId: true,
        hubId: true,
        status: true,
      },
      take: 20,
    }),
    prismaClient.vpnPeer.findMany({
      where: {
        deletedAt: null,
        enabled: true,
        server: {
          scopeId: { in: scopeIds },
          deletedAt: null,
          name: { contains: query.trim(), mode: "insensitive" },
        },
      },
      include: {
        server: {
          select: {
            id: true,
            name: true,
            scopeId: true,
          },
        },
      },
      take: 20,
    }),
    prismaClient.server.findMany({
      where: {
        scopeId: { in: scopeIds },
        deletedAt: null,
        name: { contains: query.trim(), mode: "insensitive" },
      },
      select: {
        id: true,
        name: true,
        scopeId: true,
      },
      take: 20,
    }),
    prismaClient.resourceScope.findMany({
      where: {
        id: { in: scopeIds },
        deletedAt: null,
        name: { contains: query.trim(), mode: "insensitive" },
      },
      select: {
        id: true,
        name: true,
      },
      take: 20,
    }),
  ]);

  let resources: Array<{ id: string; name: string; scopeId: string; type: string; phase: string }> = [];
  try {
    resources = await prismaClient.resource.findMany({
      where: {
        scopeId: { in: scopeIds },
        deletedAt: null,
        name: { contains: query.trim(), mode: "insensitive" },
      },
      select: {
        id: true,
        name: true,
        scopeId: true,
        type: true,
        phase: true,
      },
      take: 20,
    });
  } catch (error) {
    // Resource query failed, continue without resources
    console.error("Resource search failed:", error);
  }

  const results: Array<{
    type: "vpn_client" | "vpn_peer" | "server" | "scope" | "resource";
    id: string;
    name: string;
    scopeId: string | null;
    hubId: string | null;
    status?: string;
  }> = [];

  clients.forEach((client) => {
    results.push({
      type: "vpn_client",
      id: client.id,
      name: client.name,
      scopeId: client.scopeId,
      hubId: client.hubId,
      status: client.status,
    });
  });

  peers.forEach((peer) => {
    results.push({
      type: "vpn_peer",
      id: peer.id,
      name: peer.server.name,
      scopeId: peer.server.scopeId,
      hubId: peer.hubId,
    });
  });

  servers.forEach((server) => {
    results.push({
      type: "server",
      id: server.id,
      name: server.name,
      scopeId: server.scopeId,
      hubId: null,
    });
  });

  scopes.forEach((scope) => {
    results.push({
      type: "scope",
      id: scope.id,
      name: scope.name,
      scopeId: scope.id,
      hubId: null,
    });
  });

  resources.forEach((resource) => {
    results.push({
      type: "resource",
      id: resource.id,
      name: resource.name,
      scopeId: resource.scopeId,
      hubId: null,
      status: String(resource.phase),
    });
  });

  return results.sort((a, b) => a.name.localeCompare(b.name));
}

export class VpnError extends Error {
  constructor(
    message: string,
    public readonly statusCode: number,
  ) {
    super(message);
    this.name = "VpnError";
  }
}
